# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecf6069932bdc00b42b5aeaf75b9dca396e48c09699e073aa47c91fd480bc88b913bf7e54ab8b7c8cce2512564701badd9d16da915c3a141a3983ed2c7498e55

test:
  secret_key_base: 437ac06cd65719eb0f769a6e5bfee3730046ddb770a70f11aa4c56992313dbc17e0934400b3d5c5eb8d48432bd464b68ff838afa92d14060104537987052344c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
